services:

  apache:
    image: httpd:2.4-alpine
    ports:
      - 8083:80
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/docker.apache.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/log/apache/:/var/log/apache/
